import { User, FeedbackForm, Feedback } from '../types';

export const mockUsers: User[] = [
  {
    id: 'admin-1',
    email: 'admin@feedback.com',
    name: 'Admin User',
    role: 'admin',
  },
  {
    id: 'user-1',
    email: 'user@example.com',
    name: 'Test User',
    role: 'user',
  },
];

export const mockForms: FeedbackForm[] = [
  {
    id: 'form-1',
    title: 'Product Feedback Survey',
    description: 'Help us improve our product by sharing your experience',
    createdBy: 'admin-1',
    createdAt: '2024-01-15T10:00:00Z',
    isActive: true,
    fields: [
      {
        id: 'field-1',
        label: 'Name',
        type: 'text',
        required: true,
        placeholder: 'Enter your name',
      },
      {
        id: 'field-2',
        label: 'Email',
        type: 'email',
        required: true,
        placeholder: 'your.email@example.com',
      },
      {
        id: 'field-3',
        label: 'Message',
        type: 'textarea',
        required: true,
        placeholder: 'Share your feedback with us...',
      },
      {
        id: 'field-4',
        label: 'Rating',
        type: 'rating',
        required: true,
      },
    ],
  },
  {
    id: 'form-2',
    title: 'Customer Service Feedback',
    description: 'Rate your customer service experience',
    createdBy: 'admin-1',
    createdAt: '2024-02-01T14:30:00Z',
    isActive: true,
    fields: [
      {
        id: 'field-1',
        label: 'Name',
        type: 'text',
        required: true,
        placeholder: 'Enter your name',
      },
      {
        id: 'field-2',
        label: 'Email',
        type: 'email',
        required: true,
        placeholder: 'your.email@example.com',
      },
      {
        id: 'field-3',
        label: 'Feedback',
        type: 'textarea',
        required: true,
        placeholder: 'Tell us about your experience...',
      },
      {
        id: 'field-4',
        label: 'Overall Rating',
        type: 'rating',
        required: true,
      },
    ],
  },
];

export const mockFeedbacks: Feedback[] = [
  {
    id: 'feedback-1',
    formId: 'form-1',
    name: 'John Doe',
    email: 'john@example.com',
    message: 'Great product! Love the user interface and features.',
    rating: 5,
    createdAt: '2024-03-10T09:15:00Z',
    responses: {
      'field-1': 'John Doe',
      'field-2': 'john@example.com',
      'field-3': 'Great product! Love the user interface and features.',
      'field-4': 5,
    },
  },
  {
    id: 'feedback-2',
    formId: 'form-1',
    name: 'Jane Smith',
    email: 'jane@example.com',
    message: 'Good overall, but could use some improvements in performance.',
    rating: 4,
    createdAt: '2024-03-11T14:22:00Z',
    responses: {
      'field-1': 'Jane Smith',
      'field-2': 'jane@example.com',
      'field-3': 'Good overall, but could use some improvements in performance.',
      'field-4': 4,
    },
  },
  {
    id: 'feedback-3',
    formId: 'form-1',
    name: 'Mike Johnson',
    email: 'mike@example.com',
    message: 'The product crashed multiple times. Very disappointed.',
    rating: 2,
    createdAt: '2024-03-12T11:45:00Z',
    responses: {
      'field-1': 'Mike Johnson',
      'field-2': 'mike@example.com',
      'field-3': 'The product crashed multiple times. Very disappointed.',
      'field-4': 2,
    },
  },
  {
    id: 'feedback-4',
    formId: 'form-1',
    name: 'Sarah Williams',
    email: 'sarah@example.com',
    message: 'Excellent service and support team. Highly recommend!',
    rating: 5,
    createdAt: '2024-03-13T16:30:00Z',
    responses: {
      'field-1': 'Sarah Williams',
      'field-2': 'sarah@example.com',
      'field-3': 'Excellent service and support team. Highly recommend!',
      'field-4': 5,
    },
  },
  {
    id: 'feedback-5',
    formId: 'form-1',
    name: 'David Brown',
    email: 'david@example.com',
    message: 'Average experience. Nothing special but works as expected.',
    rating: 3,
    createdAt: '2024-03-14T10:00:00Z',
    responses: {
      'field-1': 'David Brown',
      'field-2': 'david@example.com',
      'field-3': 'Average experience. Nothing special but works as expected.',
      'field-4': 3,
    },
  },
  {
    id: 'feedback-6',
    formId: 'form-1',
    name: 'Emily Davis',
    email: 'emily@example.com',
    message: 'Love the features! Would like to see dark mode added.',
    rating: 4,
    createdAt: '2024-03-15T13:20:00Z',
    responses: {
      'field-1': 'Emily Davis',
      'field-2': 'emily@example.com',
      'field-3': 'Love the features! Would like to see dark mode added.',
      'field-4': 4,
    },
  },
  {
    id: 'feedback-7',
    formId: 'form-1',
    name: 'Robert Wilson',
    email: 'robert@example.com',
    message: 'Not satisfied. The interface is confusing and slow.',
    rating: 2,
    createdAt: '2024-03-16T08:45:00Z',
    responses: {
      'field-1': 'Robert Wilson',
      'field-2': 'robert@example.com',
      'field-3': 'Not satisfied. The interface is confusing and slow.',
      'field-4': 2,
    },
  },
  {
    id: 'feedback-8',
    formId: 'form-1',
    name: 'Lisa Anderson',
    email: 'lisa@example.com',
    message: 'Perfect! Exactly what I needed. Thank you!',
    rating: 5,
    createdAt: '2024-03-17T15:10:00Z',
    responses: {
      'field-1': 'Lisa Anderson',
      'field-2': 'lisa@example.com',
      'field-3': 'Perfect! Exactly what I needed. Thank you!',
      'field-4': 5,
    },
  },
  {
    id: 'feedback-9',
    formId: 'form-2',
    name: 'Tom Martinez',
    email: 'tom@example.com',
    message: 'Customer service was helpful and responsive.',
    rating: 4,
    createdAt: '2024-03-18T12:00:00Z',
    responses: {
      'field-1': 'Tom Martinez',
      'field-2': 'tom@example.com',
      'field-3': 'Customer service was helpful and responsive.',
      'field-4': 4,
    },
  },
  {
    id: 'feedback-10',
    formId: 'form-2',
    name: 'Anna Taylor',
    email: 'anna@example.com',
    message: 'Had to wait too long for a response. Not happy.',
    rating: 2,
    createdAt: '2024-03-19T09:30:00Z',
    responses: {
      'field-1': 'Anna Taylor',
      'field-2': 'anna@example.com',
      'field-3': 'Had to wait too long for a response. Not happy.',
      'field-4': 2,
    },
  },
];
